services:
  rabbitmq:
    extends:
      file: RabbitMQ/docker-compose.yml
      service: rabbitmq
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: kms_redis
    networks:
      - kms_service_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #######################
  # DATABASE
  ########################

  gateway_db:
    extends:
      file: ./fastapi-gateway/docker-compose.yml
      service: gateway_db
    env_file: .env

  gateway-redis:
    extends:
      file: ./fastapi-gateway/docker-compose.yml
      service: gateway-redis
    env_file: .env
    networks:
      - gateway_net
      - internal

  users-service_db:
    extends:
      file: ./users-service/docker-compose.yml
      service: users-service_db
    env_file: .env

  schools-service_db:
    extends:
      file: ./schools-service/docker-compose.yml
      service: schools-service_db
    env_file: .env

  ########################
  # MIGRAZIONI
  ########################

  gateway-migrate:
    extends:
      file: ./fastapi-gateway/docker-compose.yml
      service: gateway-migrate
    env_file: .env

  users-service-migrate:
    extends:
      file: ./users-service/docker-compose.yml
      service: users-service-migrate
    env_file: .env

  schools-service-migrate:
    extends:
      file: ./schools-service/docker-compose.yml
      service: schools-service-migrate
    env_file: .env
    ########################
    # SERVIZI
    ########################

  gateway:
    extends:
      file: ./fastapi-gateway/docker-compose.yml
      service: gateway
    env_file: .env
    networks:
      - backend_net
      - rabbit_net
      - gateway_net
      - internal

  kms-service_db:
    extends:
      file: ./KMS-service/docker-compose.yml
      service: kms-service_db
    env_file: .env

  kms-service-migrate:
    extends:
      file: ./KMS-service/docker-compose.yml
      service: kms-service-migrate
    env_file: .env

  kms-service:
    extends:
      file: ./KMS-service/docker-compose.yml
      service: kms-service
    env_file: .env
    networks:
      - backend_net
      - rabbit_net
      - kms_service_net
    deploy:
      replicas: 1
    restart: unless-stopped

  users-service:
    extends:
      file: ./users-service/docker-compose.yml
      service: users-service
    env_file: .env
    networks:
      - backend_net
      - rabbit_net
      - users_service_net

  schools-service:
    extends:
      file: ./schools-service/docker-compose.yml
      service: schools-service
    env_file: .env
    networks:
      - backend_net
      - rabbit_net
      - schools_service_net

  email-service:
    extends:
      file: ./email-service/docker-compose.yml
      service: email-service
    env_file: .env
    networks:
      - backend_net
      - rabbit_net

networks:
  gateway_net:
  users_service_net:
  schools_service_net:
  kms_service_net:
  backend_net:
  rabbit_net:
  internal:
    internal: true

volumes:
  gateway_db_data:
  users_service_db_data:
  schools_service_db_data:
  kms_service_db_data:
