services:
  rabbitmq:
    extends:
      file: RabbitMQ/docker-compose.yml
      service: rabbitmq
    restart: unless-stopped


  #######################
  # DATABASE
  ########################

  gateway_db:
    extends:
      file: ./fastapi-gateway/docker-compose.yml
      service: gateway_db
    env_file: .env

  users-service_db:
    extends:
      file: ./users-service/docker-compose.yml
      service: users-service_db
    env_file: .env

  ########################
  # MIGRAZIONI
  ########################

  gateway-migrate:
    extends:
      file: ./fastapi-gateway/docker-compose.yml
      service: gateway-migrate
    env_file: .env

  users-service-migrate:
    extends:
      file: ./users-service/docker-compose.yml
      service: users-service-migrate
    env_file: .env



    ########################
    # SERVIZI
  ########################

  gateway:
    extends:
      file: ./fastapi-gateway/docker-compose.yml
      service: gateway
    env_file: .env
    networks:
      - backend_net
      - rabbit_net
      - gateway_net


  kms-service:
    build: ./KMS-service
    env_file: .env
    networks:
      - backend_net
    deploy:
      replicas: 1   # forza una sola istanza, altrimenti si avrebbero certificati diversi
    restart: unless-stopped


  users-service:
    extends:
      file: ./users-service/docker-compose.yml
      service: users-service
    env_file: .env
    networks:
      - backend_net
      - rabbit_net
      - users_service_net


networks:
  gateway_net:
  users_service_net:
  backend_net:
  rabbit_net:

volumes:
  gateway_db_data:
  users_service_db_data: